name: ModifyJoinLeftMessages
version: '${project.version}'
main: org.doren.modifyjoinleftmessages.ModifyJoinLeftMessages
api-version: '1.16'
softdepend: [PlaceholderAPI]
commands:
  mjlm:
    description: Reload ModifyJoinLeftMessages config
    usage: /mjlm reload
    permission: modifyjoinleftmessages.reload
permissions:
  modifyjoinleftmessages.base:
    description: Access ModifyJoinLeftMessages commands
    default: true
  modifyjoinleftmessages.reload:
    description: Reload ModifyJoinLeftMessages config
    default: op
